version: "3.9"

services:
    node:
        env_file: .env
        build: .
        expose:
            - 5000
        environment:
            DB: mongodb://db/portfo
            REDIS: redis://cache
        volumes:
            - .:/home/server/app
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - db
            - cache
    # server_test:
    #     image: portfo_server
    #     environment:
    #         DB: mongodb://db/portfo_test
    #         REDIS: redis://cache
    #     volumes:
    #         - .:/home/server/app
    #     command: npm run docker-test
    #     depends_on:
    #         - server
    #         - db
    #         - cache
    db:
        image: mongo:4.4.8-focal
        expose:
            - 27017
        volumes:
            - ./db:/data/db
    cache:
        image: redis:alpine
        expose:
            - 6379
        restart: always
        depends_on:
            - db
    nginx:
        build:
            dockerfile: ./nginx/Dockerfile
            context: ./
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 80:80
            - 443:443
        depends_on:
            - node