version: "3.9"

services:
    server:
        env_file: .env
        build: .
        ports:
            - 80:5000
        environment:
            DB: mongodb://db/portfo
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: mongo:4.4.8-focal
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db